Models/Article.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace ASPDotNetApp.Models
{
    public class Article
    {
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        [Required]
        [DisplayName("VAT percentage")]
        [Range(0, 999.99, ErrorMessage = "VAT percentage must be between 0 and 999.99 only!")]
        public decimal VATPercentage { get; set; }
        [DisplayName("Purchase price")]
        [Range(0, 9999999999999999.99, ErrorMessage = "Purchase price must be between 0 and 9999999999999999.99 only!")]
        public decimal? PurchasePrice { get; set; }
        [DisplayName("Retail price")]
        [Range(0, 9999999999999999.99, ErrorMessage = "Retail price must be between 0 and 9999999999999999.99 only!")]
        public decimal? RetailPrice { get; set; }
        [Required]
        public bool Status { get; set; }
    }
}

Controllers/ArticlesController.cs
using ASPDotNetApp.Daos;
using ASPDotNetApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPDotNetApp.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly IArticleDao _articleDao;

        public ArticlesController(IArticleDao articleDao)
        {
            _articleDao = articleDao;
        }

        // GET: ArticlesController
        public async Task<IActionResult> Index()
        {
            var articlesList = await _articleDao.GetAll();
            return View(articlesList);
        }

        // GET: ArticlesController/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ArticlesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Article article)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var isCreateSuccessful = await _articleDao.Add(article);
                    if (isCreateSuccessful)
                    {
                        TempData["success"] = $"Article {article.Name} created successfully";
                    }
                    else
                    {
                        TempData["error"] = $"Error creating Article {article.Name}!";
                    }
                }
                catch (Exception ex)
                {
                    TempData["error"] = $"Database error: {ex.Message}";
                }
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: ArticlesController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var articleFromDb = await _articleDao.Get(id);
            if (articleFromDb == null)
            {
                return NotFound();
            }
            return View(articleFromDb);
        }

        // POST: ArticlesController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Article article)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var isUpdateSuccessful = await _articleDao.Update(article);
                    if (isUpdateSuccessful)
                    {
                        TempData["succes"] = $"Article {article.Name} updated successfully";
                    }
                    else
                    {
                        TempData["error"] = $"Error updating Article {article.Name}!";
                    }
                }
                catch (Exception ex)
                {
                    TempData["error"] = $"Database error: {ex.Message}";
                }                
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: ArticlesController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var articleFromDb = await _articleDao.Get(id);
            if (articleFromDb == null)
            {
                return NotFound();
            }
            return View(articleFromDb);
        }

        // POST: ArticlesController/DeletePost/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int id)
        {
            var isDeleteSuccessful = await _articleDao.Delete(id);
            if (isDeleteSuccessful)
            {
                TempData["success"] = "Article deleted successfully";
            }
            else
            {
                TempData["error"] = "Error deleting article!";
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/PriceListsController.cs
using ASPDotNetApp.Daos;
using ASPDotNetApp.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ASPDotNetApp.Controllers
{
    public class PriceListsController : Controller
    {
        private readonly IPriceListDao _priceListDao;
        private readonly IArticleDao _articleDao;

        public PriceListsController(IPriceListDao priceListDao, IArticleDao articleDao)
        {
            _priceListDao = priceListDao;
            _articleDao = articleDao;
        }               

        // GET: PriceListController/5
        public async Task<IActionResult> Index(int id)
        {
            var priceLists = await _priceListDao.GetAll(id);
            var article = await _articleDao.Get(id);
            var dataTuple = new Tuple<Article, IEnumerable<PriceList>>(article, priceLists);
            return View(dataTuple);
        }

        // GET: PriceListController/Create
        public IActionResult Create(int articleId)
        {
            ViewBag.ArticleId = articleId;
            return View();
        }

        // POST: PriceListController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PriceList priceList)
        {
            if (ModelState.IsValid)
            {
                var isCreateSuccessful = await _priceListDao.Add(priceList);
                if (isCreateSuccessful)
                {
                    TempData["success"] = "Price list created successfully";
                    return RedirectToAction("Index", new { id = priceList.ArticleId });
                }
                else
                {
                    TempData["error"] = "Error creating Price list";
                }
            }
            ViewBag.ArticleId = priceList.ArticleId;
            return View(priceList);
        }

        // GET: PriceListController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var priceListFromDb = await _priceListDao.Get(id);
            if (priceListFromDb == null)
            {
                return NotFound();
            }
            ViewBag.ArticleId = priceListFromDb.ArticleId;
            return View(priceListFromDb);
        }

        // POST: PriceListController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PriceList priceList)
        {
            if (ModelState.IsValid)
            {
                var isUpdateSuccessful = await _priceListDao.Update(priceList);
                if (isUpdateSuccessful)
                {
                    TempData["success"] = "Price list updated successfully";
                }
                else
                {
                    TempData["error"] = "Error updating Price list!";
                }
                return RedirectToAction("Index", new { id = priceList.ArticleId });
            }
            ViewBag.ArticleId = priceList.ArticleId;
            return View(priceList);
        }

        // GET: PriceListController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var priceListFromDb = await _priceListDao.Get(id);
            if (priceListFromDb == null)
            {
                return NotFound();
            }
            ViewBag.ArticleId = priceListFromDb.ArticleId;
            return View(priceListFromDb);
        }

        // POST: PriceListController/DeletePost/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePost(int id)
        {
            var priceListFromDb = await _priceListDao.Get(id);
            var articleId = priceListFromDb?.ArticleId;
            var isDeleteSuccessful = await _priceListDao.Delete(id);
            if (isDeleteSuccessful)
            {
                TempData["success"] = "Price list deleted successfully";
            }
            else
            {
                TempData["error"] = "Error deleting price list!";
            }
            return RedirectToAction("Index", new { id = articleId });
        }

        // GET: PriceListController/Prices
        public async Task<IActionResult> SearchByDate(DateTime searchDate)
        {
            var priceLists = await _priceListDao.SearchValidPrices(searchDate);
            ViewBag.SearchDate = searchDate;
            return View(priceLists);
        }
    }
}

Views/Articles/Create.cshtml
@model Article

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Article</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Code"></label>
            <input asp-for="Code" class="form-control" />
            <span asp-validation-for="Code" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="VATPercentage"></label>
            <input asp-for="VATPercentage" type="number" class="form-control" />
            <span asp-validation-for="VATPercentage" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PurchasePrice"></label>
            <input asp-for="PurchasePrice" type="number" class="form-control" />
            <span asp-validation-for="PurchasePrice" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="RetailPrice"></label>
            <input asp-for="RetailPrice" type="number" class="form-control" />
            <span asp-validation-for="RetailPrice" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Status"></label>
            <input asp-for="Status" type="checkbox" class="form-check-input" checked />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-controller="Articles" asp-action="Index" class="btn btn-light" style="width:150px">Back to List</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Articles/Delete.cshtml
@model Article

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Article</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Code"></label>
            <input asp-for="Code" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="VATPercentage"></label>
            <input asp-for="VATPercentage" type="number" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="PurchasePrice"></label>
            <input asp-for="PurchasePrice" type="number" disabled class="form-control" />
        <div class="mb-3">
            <label asp-for="RetailPrice"></label>
            <input asp-for="RetailPrice" type="number" disabled class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Status"></label>
            <input asp-for="Status" type="checkbox" disabled class="form-check-input" />
        </div>
        <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
        <a asp-controller="Articles" asp-action="Index" class="btn btn-light" style="width:150px">Back to List</a>
    </div>
</form>

Views/Articles/Edit.cshtml
@model Article

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Article</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Code"></label>
            <input asp-for="Code" class="form-control" />
            <span asp-validation-for="Code" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="VATPercentage"></label>
            <input asp-for="VATPercentage" type="number" class="form-control" />
            <span asp-validation-for="VATPercentage" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="PurchasePrice"></label>
            <input asp-for="PurchasePrice" type="number" class="form-control" />
            <span asp-validation-for="PurchasePrice" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="RetailPrice"></label>
            <input asp-for="RetailPrice" type="number" class="form-control" />
            <span asp-validation-for="RetailPrice" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Status"></label>
            <input asp-for="Status" type="checkbox" class="form-check-input" />
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Articles" asp-action="Index" class="btn btn-light" style="width:150px">Back to List</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Articles/Index.cshtml
@model IEnumerable<Article>
@{
    ViewData["Title"] = "Articles Page";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Articles List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Articles" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle"></i> &nbsp; Create New Article
            </a>
        </div>
    </div>
    <br /> <br />

    <table class="table table-active">
        <thead>
            <tr>
                <th>Name</th>
                <th>Code</th>
                <th>VAT Percentage</th>
                <th>Purchase Price</th>
                <th>Retail Price</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var article in Model)
            {
                <tr class=@(article.Status ? "" : "table-secondary")>
                    <td><a asp-controller="PriceLists" asp-action="Index" asp-route-id="@article.Id"
                    class="btn btn-info" style="width:90%">
                            <i class="bi bi-info-circle"></i> @article.Name
                        </a>
                    </td>
                    <td>@article.Code</td>
                    <td>@article.VATPercentage</td>
                    <td>@if (article.PurchasePrice.HasValue)
                        {
                            @article.PurchasePrice
                        }
                        else
                        {
                            <span>none</span>
                        }
                    </td>
                    <td>@if (article.RetailPrice.HasValue)
                        {
                            @article.RetailPrice
                        }
                        else
                        {
                            <span>none</span>
                        }
                    </td>
                    <td>@(article.Status ? "Active" : "Inactive")</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a asp-controller="Articles" asp-action="Edit" asp-route-id="@article.Id"
                            class="btn btn-warning">
                                <i class="bi bi-pencil-square"></i> Edit
                            </a>
                            <a asp-controller="Articles" asp-action="Delete" asp-route-id="@article.Id"
                            class="btn btn-danger">
                                <i class="bi bi-trash-fill"></i> Delete
                            </a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>